
all:
	go build

tarit:
	tar -cf ../ex-pkg.tar .gitignore Makefile err.01.md go.mod go.sum main.go testPkg
	rm -f ../ex-pkg.zip
	zip -r ../ex-pkg.zip ./.gitignore ./Makefile ./err.01.md ./go.mod ./go.sum ./main.go ./testPkg


